name: ipyrad
channels: 
  - conda-forge
  - bioconda
  - eaton-lab
dependencies:
  - python>=3.7
  - ipython
  - jupyter
  - pydantic
  - loguru
  - requests
  - h5py
  - toyplot
  - toytree
  - pandas
  - scipy
  - numpy
  - numba
  - ipyparallel >=7.0

  - pysam >=0.15
  - vsearch >=2.13
  - bedtools
  - muscle
  - fastp
  - bwa
  - samtools
  - zlib

  - raxml
  - openjdk

  - pip
  - pip:
    - git+https://github.com/dereneaton/ipyrad.git@rejson#egg=ipyrad
    - git+https://github.com/eaton-lab/toytree.git@toy3#egg=toytree
    - git+https://github.com/eaton-lab/ipcoal.git@toy3#egg=ipcoal


